### ISSUE TITLE
fails w/o initial zeros

### ISSUE THREAD

**Issue by stevesmoot** [soniah/evaler#6]
.5 \* 2 comes out as 10
fix is 
var fp_rx = regexp.MustCompile(`([0-9]*\.?[0-9]+)`)  
I believe.
(and add a test like):
    {".5 \* 2", big.NewRat(1, 1), true},           // no leading zero   

tried to submit, but I clearly dont know how to use github yet...so submitting as issue.
-s

**Comment by soniah** [comment]
Thanks @stevesmoot  and sorry about the years-long delay. Anyway, I've merged in some code that fixes this.
