### ISSUE TITLE
Add support for trigonometric and logarithmic functions

### ISSUE THREAD

**Issue by thecardinelli** [soniah/evaler#9]
e.g.
sin(1) = 0.84
sin(0) = 0
...
ln(0) = 1

**Comment by soniah** [comment]
Hi dem-waffles/thecardinelli. Sorry I ignored you PR for several years... Family, life, excuses, excuses...

Anyway, I've pulled in your trig code (not the variables stuff) and given you authorship - see `git log`, `git blame` and the README.
